### ISSUE TITLE
导出表结构到指定文件

### ISSUE THREAD

**Issue by wangkaili123** [polardb/polardbx-tools#16]
1.导出表结构，指定参数-t table_name -ddl only ，默认在当前目录下生成db_name.ddl文件，-f参数不生效，无法指定导出文件名称以及位置；
2.导入表结构 指定 -t table_name -ddl only  -f ddl.ddl，提示table_name.ddl不存在，-f 参数不生效，无法指定导入文件名称以及位置；

3.导出表结构不支持create table前设置drop table if exist table_name；

**Comment by F-ca7** [comment]
1. `-f`参数只能指定导入时的文件列表，无法指定导出文件名称；可以设置`-dir`参数来指定导出的文件目录
2. 【WIP】待修复
3. 新增参数 `-dropTableIfExist true`来支持在create table前设置drop table if exists table_name，该选项默认关闭，避免误操作把有数据的表删了

**Comment by F-ca7** [comment]
2. 导入表结构，只支持-D 指定数据库，不支持使用 -t table_name 指定表名，导入的表结构只由DDL文件里的建表SQL决定
