### ISSUE TITLE
表中json字段导入导出后数据不一致

### ISSUE THREAD

**Issue by wangkaili123** [polardb/polardbx-tools#17]
表中json字段导入导出后数据不一致，源数据"delivery.types":"[\"SELF_PICK\"]" -> 目标数据"delivery.types":"[\\"SELF_PICK\\"]"

源数据：
![image](https://github.com/polardb/polardbx-tools/assets/18457556/dd1a6ec0-f8f2-40d0-a433-a6790447e233)

目标数据：
![image](https://github.com/polardb/polardbx-tools/assets/18457556/65a737ba-1521-4a59-a003-c959671c88ee)

**Comment by F-ca7** [comment]
自v1.3.3版本起修复
