### ISSUE TITLE
导入时使用 --DDL with不起作用，不支持同时导入表结构和表数据;

### ISSUE THREAD

**Issue by wangkaili123** [polardb/polardbx-tools#18]
1.导出时支持使用 --DDL with ,同时导出表结构和表数据。导入时使用 --DDL with不起作用，不支持同时导入表结构和表数据;
2.指定--ddl only 参数，导入表结构时，只支持-D ，指定-t参数，报错：Failed to read from finance_settlement_order.ddl;
3.指定--ddl only参数，导入表结构时，只支持-f参数，不支持指定-dir，否则报错：Import database DDL only support one ddl file now!;

**Comment by F-ca7** [comment]
1. 在下一个版本修复，导入时使用 --DDL with 配合 -dir 指定之前已经整库导出的目录，可进行整库导入
2. ddl文件里面的语句都是 create table xxx，不支持-t指定表导入DDL，只能在某个库里面建ddl文件里的表
3. 在下一个版本修复，之前的设计只支持一个库一次只导入一个DDL文件（通常按库导出的DDL文件只有一个），修复后 导入DDL可以指定-dir 导入多个DDL文件（按照 `.ddl` 文件后缀进行区分）

**Comment by UchihaYong** [comment]
问题修复了吗，为啥我现在用jar包还是代码debug都不能同时导入表结构和表数据。一开始没有数据库，期望创建，但-D指定数据库在连接时会报“数据库不存在，无法连接”。如果不指定要导入的schema，在后续查看表列元数据列表的时候会时空，导致报错“required field size 0, actual size 11”
