### ISSUE TITLE
导出时按行分隔文件后无法导入

### ISSUE THREAD

**Issue by dsk2866** [polardb/polardbx-tools#24]
导出时设置参数 -sharding false -L 5000000   
会生成 类似下面的文件名：
tableName_0-0, tableName_0-1,tableName_0-0, tableName_0-2,
由于文件名超过表名两个长度，导致指定目录导入时，无法导入数据。报下面的错误：
No filename with suffix starts with table name: tableName

**Comment by ytk929** [comment]
同问，我这边报的错误是
Skip table tableName operation since no filename matches

**Comment by ytk929** [comment]
同问，我这边整库导入报的错误是
Skip table tableName operation since no filename matches

**Comment by F-ca7** [comment]
> 导出时设置参数 -sharding false -L 5000000 会生成 类似下面的文件名： tableName_0-0, tableName_0-1,tableName_0-0, tableName_0-2, 由于文件名超过表名两个长度，导致指定目录导入时，无法导入数据。报下面的错误： No filename with suffix starts with table name: tableName

这个问题将在 V1.4.1 版本有绕过的方法

其原因是：BatchTool 为了适配自身整库导出的文件名规则，要求文件名必须以表名开头，且文件名后缀满足一定规则（如分区表的分区下标），但是有些case没考虑到

**Comment by F-ca7** [comment]
> 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches

整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题

**Comment by F-ca7** [comment]
> > 导出时设置参数 -sharding false -L 5000000 会生成 类似下面的文件名： tableName_0-0, tableName_0-1,tableName_0-0, tableName_0-2, 由于文件名超过表名两个长度，导致指定目录导入时，无法导入数据。报下面的错误： No filename with suffix starts with table name: tableName
> 
> 这个问题将在 V1.4.1 版本有绕过的方法
> 
> 其原因是：BatchTool 为了适配自身整库导出的文件名规则，要求文件名必须以表名开头，且文件名后缀满足一定规则（如分区表的分区下标），但是有些case没考虑到

可参考文档：[常见问题排查](https://github.com/polardb/polardbx-tools/blob/main/batch-tool/docs/usage-details.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%8E%92%E6%9F%A5)，导入时可指定参数--prefix "${文件名前缀}"来指定目录里与导入表匹配的文件名前缀

**Comment by ytk929** [comment]
> > 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches
> 
> 整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题

可能是一个问题吧，我没说清楚。
整库导出加入-L按行分隔后，再整库导入就会报Skip table tableName operation since no filename matches
单表导出加入-L按行分隔后，再单表导入就会报No filename with suffix starts with table name: tableName

**Comment by ytk929** [comment]
> > 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches
> 
> 整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题

可能是一个问题吧，我没说清楚。
整库导出加入-L按行分隔后，再整库导入就会报Skip table tableName operation since no filename matches
单表导出加入-L按行分隔后，再单表导入就会报No filename with suffix starts with table name: tableName
表的名字都是tableName_0-数字

**Comment by F-ca7** [comment]
> > > 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches
> > 
> > 
> > 整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题
> 
> 可能是一个问题吧，我没说清楚。 整库导出加入-L按行分隔后，再整库导入就会报Skip table tableName operation since no filename matches 单表导出加入-L按行分隔后，再单表导入就会报No filename with suffix starts with table name: tableName 表的名字都是tableName_0-数字

明白了，恐怕这个新版本还解决不了整库导出指定最大行数的问题 :disappointed_relieved:，目前只解决了单表的

**Comment by ytk929** [comment]
> > > > 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches
> > > 
> > > 
> > > 整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题
> > 
> > 
> > 可能是一个问题吧，我没说清楚。 整库导出加入-L按行分隔后，再整库导入就会报Skip table tableName operation since no filename matches 单表导出加入-L按行分隔后，再单表导入就会报No filename with suffix starts with table name: tableName 表的名字都是tableName_0-数字
> 
> 明白了，恐怕这个新版本还解决不了整库导出指定最大行数的问题 😥，目前只解决了单表的

ok，加油

**Comment by F-ca7** [comment]
> > > 同问，我这边整库导入报的错误是 Skip table tableName operation since no filename matches
> > 
> > 
> > 整库导出导入文件名匹配不上的现象是什么，正常来说 tableA、tableB 导出来的文件名是 tableA_0、tableB_0 这样子，和上面那个指定了最大行数的导出可能不是一个问题
> 
> 可能是一个问题吧，我没说清楚。 整库导出加入-L按行分隔后，再整库导入就会报Skip table tableName operation since no filename matches 单表导出加入-L按行分隔后，再单表导入就会报No filename with suffix starts with table name: tableName 表的名字都是tableName_0-数字

"整库导出加入-L按行分隔后，导入失败"——这个问题将在 V1.4.2 中修复

**Comment by F-ca7** [comment]
在 V1.4.2 中修复，同样的导入时可指定参数--prefix "${文件名前缀}"来指定目录里与导入表匹配的文件名前缀
