### ISSUE TITLE
frodo编译失败

### ISSUE THREAD

**Issue by fengluodb** [polardb/polardbx-tools#28]
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/bc62f421-1b55-42d9-a91f-0e0ba45b09d9">

# java版本
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)

**Comment by F-ca7** [comment]
估计是 lombok 不支持 jdk21，还是试试jdk8吧

**Comment by fengluodb** [comment]
使用jdk8后可以成功编译
